eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


microservices:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/api/v1/payments/payment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/api/v1/order/bookOrder
